const PROJECT_NAME = 'NutrImprove';
const ROLES = {
  OWNER: 0,
  ADMIN: 5,
  CONTRIBUTOR: 100,
};
const INPUT_TRIGGER_TIME = 700;
const MIN_WIDTH = 800;

export { PROJECT_NAME, ROLES, INPUT_TRIGGER_TIME, MIN_WIDTH };
